name: Playwright Tests
on:
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_TAG: lasbe/test:latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Build the Dockerfile
        run: docker build -t ${{ env.DOCKER_IMAGE_TAG }} --build-arg="NEXT_PUBLIC_API_URL_OP=${{ secrets.NEXT_PUBLIC_API_URL_OP }}" .

      - name: Run Docker Container
        run: docker run -d --name test -p 3000:3000 ${{ env.DOCKER_IMAGE_TAG }}

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm playwright install chromium --with-deps

      - name: Run Playwright tests
        run: pnpm test:e2e

      - name: Stop And Remove Docker Container
        run: |
          docker stop test
          docker rm test

      - uses: daun/playwright-report-summary@v3
        name: "Playwright Reporter"
        with:
          report-file: results.json
          comment-title: "Playwright E2E Test Results"
          job-summary: true
